import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { createSign } from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ─── QZ Tray Signing Endpoint ────────────────────────────────
// Signs print requests using the private key generated by QZ Tray.
//
// SETUP (one-time):
// 1. Open QZ Tray on your Mac
// 2. Click the QZ icon in menu bar → Advanced → Site Manager
// 3. Click "+" to create new certificate
// 4. Save the generated files:
//    - Copy "digital-certificate.txt" → server/signing/digital-certificate.txt
//    - Copy "private-key.pem"         → server/signing/private-key.pem
// 5. Restart the server
// ─────────────────────────────────────────────────────────────

const SIGNING_DIR = join(__dirname, '..', 'signing');
const CERT_PATH = join(SIGNING_DIR, 'digital-certificate.txt');
const KEY_PATH = join(SIGNING_DIR, 'private-key.pem');

let privateKey = null;
let certificate = null;

// Load signing files if they exist
export function loadSigningFiles() {
  try {
    if (existsSync(CERT_PATH)) {
      certificate = readFileSync(CERT_PATH, 'utf8').trim();
      console.log('  ✅ QZ Tray certificate loaded');
    } else {
      console.log('  ⚠️  No QZ certificate found at:', CERT_PATH);
      console.log('     → Generate one via QZ Tray → Advanced → Site Manager');
    }

    if (existsSync(KEY_PATH)) {
      privateKey = readFileSync(KEY_PATH, 'utf8').trim();
      console.log('  ✅ QZ Tray private key loaded');
    } else {
      console.log('  ⚠️  No QZ private key found at:', KEY_PATH);
    }
  } catch (err) {
    console.error('  ❌ Error loading QZ signing files:', err.message);
  }
}

/**
 * Sign a message using the QZ Tray private key.
 * @param {string} toSign - The string to sign (provided by QZ Tray)
 * @returns {string|null} Base64-encoded signature
 */
export function signMessage(toSign) {
  if (!privateKey) return null;

  try {
    const sign = createSign('SHA512');
    sign.update(toSign);
    return sign.sign(privateKey, 'base64');
  } catch (err) {
    console.error('  ❌ QZ signing error:', err.message);
    return null;
  }
}

/**
 * Get the certificate content.
 * @returns {string|null}
 */
export function getCertificate() {
  return certificate;
}

/**
 * Check if signing is configured.
 * @returns {boolean}
 */
export function isSigningConfigured() {
  return !!(privateKey && certificate);
}
